"""
ntfy.sh Two-Way Remote Controller
---------------------------------
Listens for incoming command messages published to an ntfy topic via real-time stream:
- init / start   : Triggers live chat monitoring (starts the bot)
- stop / pause   : Stops / pauses monitoring
- status         : Publishes current bot state & stream status back to ntfy
- channel <name> : Switches monitored channel dynamically
- keywords <kws> : Updates watched keywords on the fly
- help           : Displays available commands

100% Free Forever. Zero accounts, zero API tokens, and zero open ports required.
"""

import os
import sys
import json
import time
import logging
import threading
from typing import Optional, List, Dict, Any, Tuple

import requests

from yt_live_chat_alert import (
    LiveChatAlertBot,
    NTFY_TOPIC,
)

log = logging.getLogger("ntfy_controller")


class NtfyController:
    """
    Connects to ntfy.sh streaming endpoint for a given topic,
    listens for user commands (like 'init'), and publishes responses.
    """

    def __init__(
        self,
        bot_instance: LiveChatAlertBot,
        topic: Optional[str] = None,
        server_url: str = "https://ntfy.sh",
    ):
        self.bot = bot_instance
        self.topic = (topic or NTFY_TOPIC).strip()
        self.server_url = server_url.rstrip("/")
        self._thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        self.last_handled_time = time.time() - 5.0  # Only process new messages after startup

    @property
    def is_configured(self) -> bool:
        return bool(self.topic)

    @property
    def is_running(self) -> bool:
        return self._thread is not None and self._thread.is_alive() and not self._stop_event.is_set()

    def publish_response(
        self,
        message: str,
        title: str = "YouTube Alert Bot",
        priority: int = 3,
        tags: Optional[List[str]] = None,
    ) -> bool:
        """Publish a response notification back to the ntfy topic."""
        if not self.topic:
            return False

        url = f"{self.server_url}/{self.topic}"
        payload = {
            "topic": self.topic,
            "title": title,
            "message": message,
            "priority": priority,
            "tags": tags or ["robot", "gear"],
        }

        try:
            resp = requests.post(url, json=payload, timeout=10)
            return resp.ok
        except Exception as e:
            log.error(f"Failed to publish response to ntfy topic {self.topic}: {e}")
            return False

    def is_bot_alert_message(self, text: str, title: str = "", tags: Optional[List[str]] = None) -> bool:
        """
        Detects if a message was generated by the bot itself (to avoid infinite loops).
        """
        # Check title markers
        if any(marker in title for marker in ("Live Chat:", "Streamer is LIVE!", "YouTube Alert Bot")):
            return True

        # Check tag markers used by outgoing alerts
        if tags and any(t in tags for t in ("rotating_light", "red_circle", "robot")):
            return True

        # Check message prefixes
        text_lower = text.strip().lower()
        if text.startswith(("🚨", "🔴", "🟢", "🛑", "📊", "✅", "📺", "🔑", "❓")):
            return True

        return False

    def handle_command(self, raw_text: str) -> Optional[Tuple[str, str, int]]:
        """
        Parses and executes a command string received from the ntfy topic.
        Returns (response_message, title, priority) or None if ignored.
        """
        text = raw_text.strip()
        if not text:
            return None

        parts = text.split(maxsplit=1)
        command = parts[0].lower()
        args = parts[1].strip() if len(parts) > 1 else ""

        log.info(f"Received ntfy command: '{command}' (args='{args}')")

        if command in ("init", "start", "run", "monitor"):
            success, msg = self.bot.start()
            title = "🟢 Bot Initialized" if success else "ℹ️ Bot Status"
            return msg, title, 4

        elif command in ("stop", "pause", "halt"):
            success, msg = self.bot.stop()
            return msg, "🛑 Bot Stopped", 3

        elif command in ("status", "state", "info"):
            return self.bot.get_status_text(), "📊 Bot Status Report", 3

        elif command in ("channel", "setchannel", "target"):
            if not args:
                curr = self.bot.channel or "None configured"
                return f"Current channel: {curr}\nTo change: channel @Streamer", "📺 Target Channel", 3
            success, msg = self.bot.update_channel(args)
            return msg, "✅ Channel Updated", 3

        elif command in ("keywords", "setkeywords", "kw"):
            if not args:
                kws = ", ".join(self.bot.keywords)
                return f"Keywords: {kws}\nTo update: keywords solo, 1v1, ff", "🔑 Watched Keywords", 3
            new_kws = [k.strip() for k in args.split(",") if k.strip()]
            if not new_kws:
                return "Please provide comma-separated keywords: keywords solo, 1v1, ff", "⚠️ Keywords Error", 3
            success, msg = self.bot.update_keywords(new_kws)
            return msg, "✅ Keywords Updated", 3

        elif command in ("help", "menu", "commands"):
            help_msg = (
                "YouTube Alert Bot Commands:\n\n"
                "• init / start - Trigger & start chat monitoring\n"
                "• stop - Pause chat monitoring\n"
                "• status - View bot status, channel & live state\n"
                "• channel <@handle> - Change target streamer\n"
                "• keywords <k1, k2> - Update keywords\n"
                "• help - Show this command guide"
            )
            return help_msg, "🤖 Command Guide", 3

        return None

    def _stream_loop(self) -> None:
        """Continuous stream subscriber to ntfy.sh JSON endpoint."""
        log.info(f"Connecting to ntfy stream listener for topic: {self.topic}")
        stream_url = f"{self.server_url}/{self.topic}/json"
        last_id = None

        while not self._stop_event.is_set():
            try:
                # Do NOT send since=now (causes HTTP 400). Track last_id across reconnects.
                params = {"since": last_id} if last_id else None
                resp = requests.get(stream_url, params=params, stream=True, timeout=(10, None))

                if not resp.ok:
                    log.warning(f"ntfy stream returned HTTP {resp.status_code}. Retrying in 5s...")
                    if self._stop_event.wait(5.0):
                        break
                    continue

                log.info(f"ntfy stream connection active on '{self.topic}'. Waiting for commands (type 'init' to trigger)...")

                for line in resp.iter_lines():
                    if self._stop_event.is_set():
                        break
                    if not line:
                        continue

                    try:
                        data = json.loads(line.decode("utf-8"))
                    except Exception:
                        continue

                    msg_id = data.get("id")
                    if msg_id:
                        last_id = msg_id

                    event = data.get("event")
                    if event != "message":
                        continue

                    msg_time = data.get("time", 0)
                    msg_text = data.get("message", "").strip()
                    msg_title = data.get("title", "")
                    msg_tags = data.get("tags", [])

                    # Skip messages older than our start time
                    if msg_time and msg_time < self.last_handled_time:
                        continue

                    # Skip alerts sent by the bot itself
                    if self.is_bot_alert_message(msg_text, title=msg_title, tags=msg_tags):
                        continue

                    self.last_handled_time = time.time()
                    res = self.handle_command(msg_text)
                    if res:
                        reply_body, reply_title, reply_priority = res
                        self.publish_response(
                            message=reply_body,
                            title=reply_title,
                            priority=reply_priority,
                        )

            except requests.RequestException as e:
                log.debug(f"ntfy stream disconnected ({e}). Reconnecting in 3s...")
                if self._stop_event.wait(3.0):
                    break
            except Exception as e:
                log.error(f"Unexpected error in ntfy stream listener: {e}", exc_info=True)
                if self._stop_event.wait(5.0):
                    break

        log.info("ntfy stream listener exited.")

    def start(self) -> bool:
        """Starts the ntfy listener in a background daemon thread."""
        if not self.is_configured:
            log.warning("NTFY_TOPIC is not set. ntfy remote control is disabled.")
            return False

        if self.is_running:
            return False

        self._stop_event.clear()
        self._thread = threading.Thread(target=self._stream_loop, name="ntfy_stream_poller", daemon=True)
        self._thread.start()
        log.info(f"ntfy Two-Way Controller is ACTIVE on topic: '{self.topic}'")
        return True

    def stop(self) -> None:
        """Stops the ntfy listener thread cleanly."""
        self._stop_event.set()
        if self._thread and self._thread.is_alive():
            self._thread.join(timeout=3.0)
        log.info("ntfy Two-Way Controller stopped.")
