"""
ntfy.sh Two-Way Remote Controller
---------------------------------
Listens for incoming command messages published to an ntfy topic via real-time stream:
- init / start   : Triggers live chat monitoring (starts the bot)
- stop / pause   : Stops / pauses monitoring
- status         : Publishes current bot state & stream status back to ntfy
- channel <name> : Switches monitored channel dynamically
- keywords <kws> : Updates watched keywords on the fly
- help           : Displays available commands

100% Free Forever. Zero accounts, zero API tokens, and zero open ports required.
"""

import os
import sys
import json
import time
import logging
import threading
from typing import Optional, List, Dict, Any, Tuple

import requests

from yt_live_chat_alert import (
    LiveChatAlertBot,
    NTFY_TOPIC,
)

log = logging.getLogger("ntfy_controller")


class NtfyController:
    """
    Connects to ntfy.sh streaming endpoint for a given topic,
    listens for user commands (like 'init'), and publishes responses.
    """

    def __init__(
        self,
        bot_instance: LiveChatAlertBot,
        topic: Optional[str] = None,
        server_url: Optional[str] = None,
    ):
        self.bot = bot_instance
        self.topic = (topic or NTFY_TOPIC).strip()
        env_server = os.environ.get("NTFY_SERVER", "https://ntfy.sh").strip().rstrip("/")
        self.server_url = (server_url or env_server).rstrip("/")
        self._thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        self.last_handled_time = time.time() - 5.0  # Only process new messages after startup

    @property
    def is_configured(self) -> bool:
        return bool(self.topic)

    @property
    def is_running(self) -> bool:
        return self._thread is not None and self._thread.is_alive() and not self._stop_event.is_set()

    def publish_response(
        self,
        message: str,
        title: str = "YouTube Alert Bot",
        priority: int = 3,
        tags: Optional[List[str]] = None,
    ) -> bool:
        """Publish a response notification back to the ntfy topic (with Telegram backup)."""
        if not self.topic:
            return False

        tags_list = tags or ["robot", "gear"]
        topic_url = f"{self.server_url}/{self.topic}"
        headers = {
            "Title": title,
            "Priority": str(priority),
            "Tags": ",".join(tags_list),
        }

        auth_token = os.environ.get("NTFY_AUTH_TOKEN", "").strip()
        if auth_token:
            headers["Authorization"] = f"Bearer {auth_token}"

        published = False

        # 1. Primary: Direct topic publish (standard ntfy endpoint)
        try:
            resp = requests.post(topic_url, data=message.encode("utf-8"), headers=headers, timeout=10)
            log.info(f"Published direct response to ntfy '{self.topic}': status={resp.status_code}")
            if resp.ok:
                published = True
            elif resp.status_code == 429:
                log.warning(f"ntfy.sh rate-limited (HTTP 429): {resp.text}")
        except Exception as e:
            log.error(f"Failed direct publish to ntfy topic {self.topic}: {e}")

        # 2. Fallback: Root JSON publish if direct publish failed
        if not published:
            try:
                json_headers = {"Authorization": f"Bearer {auth_token}"} if auth_token else {}
                payload = {
                    "topic": self.topic,
                    "title": title,
                    "message": message,
                    "priority": priority,
                    "tags": tags_list,
                }
                resp = requests.post(self.server_url, json=payload, headers=json_headers, timeout=10)
                log.info(f"Published response via root JSON to ntfy: status={resp.status_code}")
                if resp.ok:
                    published = True
            except Exception as e:
                log.error(f"Fallback root publish failed: {e}")

        # 3. Mirror confirmation to Telegram if configured
        tg_token = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
        tg_chat_id = os.environ.get("TELEGRAM_CHAT_ID", "").strip()
        if tg_token and tg_chat_id:
            try:
                tg_url = f"https://api.telegram.org/bot{tg_token}/sendMessage"
                requests.post(
                    tg_url,
                    json={
                        "chat_id": tg_chat_id,
                        "text": f"*{title}*\n\n{message}",
                        "parse_mode": "Markdown",
                    },
                    timeout=5,
                )
            except Exception as e:
                log.debug(f"Telegram mirror failed: {e}")

        return published

    def is_bot_alert_message(self, text: str, title: str = "", tags: Optional[List[str]] = None) -> bool:
        """
        Detects if a message was generated by the bot itself (to avoid infinite loops).
        """
        # Check title markers
        bot_titles = (
            "Live Chat:",
            "Streamer is LIVE!",
            "YouTube Alert Bot",
            "Bot Initialized",
            "Bot Status",
            "Bot Stopped",
            "Channel Updated",
            "Keywords Updated",
            "Command Guide",
            "Unknown Command",
        )
        if any(marker in title for marker in bot_titles):
            return True

        # Check tag markers used by outgoing alerts
        if tags and any(t in tags for t in ("rotating_light", "red_circle", "robot", "gear")):
            return True

        # Check message prefixes
        if text.startswith(("🚨", "🔴", "🟢", "🛑", "📊", "✅", "📺", "🔑", "❓", "🤖", "ℹ️", "⚠️")):
            return True

        return False

    def handle_command(self, raw_text: str) -> Optional[Tuple[str, str, int]]:
        """
        Parses and executes a command string received from the ntfy topic.
        Returns (response_message, title, priority) or None if ignored.
        """
        text = raw_text.strip()
        if not text:
            return None

        parts = text.split(maxsplit=1)
        command = parts[0].lower()
        args = parts[1].strip() if len(parts) > 1 else ""

        log.info(f"Received ntfy command: '{command}' (args='{args}')")

        if command in ("init", "start", "run", "monitor", "trigger", "triggered", "begin", "launch"):
            success, msg = self.bot.start()
            title = "🟢 Bot Initialized" if success else "ℹ️ Bot Status"
            return msg, title, 4

        elif command in ("stop", "pause", "halt", "kill", "off"):
            success, msg = self.bot.stop()
            return msg, "🛑 Bot Stopped", 3

        elif command in ("status", "state", "info", "report", "check", "ping"):
            return self.bot.get_status_text(), "📊 Bot Status Report", 3

        elif command in ("channel", "setchannel", "target", "streamer"):
            if not args:
                curr = self.bot.get_target_display() if hasattr(self.bot, "get_target_display") else (self.bot.channel or "None configured")
                return (
                    f"Current target: {curr}\n\n"
                    "To change, send:\n"
                    "• channel @Streamer\n"
                    "• channel UC...\n"
                    "• channel https://youtu.be/<stream_id>",
                    "📺 Target Stream / Channel",
                    3,
                )
            success, msg = self.bot.update_channel(args)
            return msg, "✅ Target Updated", 3

        elif command in ("keywords", "setkeywords", "kw"):
            if not args:
                kws = ", ".join(self.bot.keywords)
                return f"Keywords: {kws}\nTo update: keywords solo, 1v1, ff", "🔑 Watched Keywords", 3
            new_kws = [k.strip() for k in args.split(",") if k.strip()]
            if not new_kws:
                return "Please provide comma-separated keywords: keywords solo, 1v1, ff", "⚠️ Keywords Error", 3
            success, msg = self.bot.update_keywords(new_kws)
            return msg, "✅ Keywords Updated", 3

        elif command in ("help", "menu", "commands", "guide"):
            help_msg = (
                "YouTube Alert Bot Commands:\n\n"
                "• init / start - Trigger & start chat monitoring\n"
                "• stop - Pause chat monitoring\n"
                "• status - View bot state, live status, chat stats & uptime\n"
                "• channel <@handle or link> - Set streamer channel or live video link\n"
                "• keywords <k1, k2> - Update keywords (e.g. keywords solo, 1v1)\n"
                "• help - Show this command guide"
            )
            return help_msg, "🤖 Command Guide", 3

        else:
            return (
                f"Unrecognized command: '{command}'\n\n"
                "Available commands:\n"
                "• init / start - Start monitoring\n"
                "• status - Check current status\n"
                "• stop - Pause monitoring\n"
                "• channel <@handle or link> - Change target\n"
                "• keywords <k1, k2> - Update keywords\n"
                "• help - View command guide",
                "🤖 Unknown Command",
                2,
            )

    def _stream_loop(self) -> None:
        """Continuous stream subscriber to ntfy.sh JSON endpoint."""
        log.info(f"Connecting to ntfy stream listener for topic: {self.topic}")
        stream_url = f"{self.server_url}/{self.topic}/json"
        last_id = None
        seen_ids = set()

        while not self._stop_event.is_set():
            try:
                # Do NOT send since=now (causes HTTP 400). Track last_id across reconnects.
                params = {"since": last_id} if last_id else None
                resp = requests.get(stream_url, params=params, stream=True, timeout=(15, None))

                if not resp.ok:
                    log.warning(f"ntfy stream returned HTTP {resp.status_code}. Retrying in 5s...")
                    if self._stop_event.wait(5.0):
                        break
                    continue

                log.info(f"ntfy stream connection active on '{self.topic}'. Waiting for commands (type 'init' or 'status')...")

                for line in resp.iter_lines(chunk_size=1):
                    if self._stop_event.is_set():
                        break
                    if not line:
                        continue

                    try:
                        data = json.loads(line.decode("utf-8"))
                    except Exception:
                        continue

                    msg_id = data.get("id")
                    if msg_id:
                        if msg_id in seen_ids:
                            continue
                        seen_ids.add(msg_id)
                        last_id = msg_id
                        if len(seen_ids) > 2000:
                            seen_ids = set(list(seen_ids)[-1000:])

                    event = data.get("event")
                    if event != "message":
                        continue

                    msg_text = data.get("message", "").strip()
                    msg_title = data.get("title", "")
                    msg_tags = data.get("tags", [])

                    # Skip alerts sent by the bot itself
                    if self.is_bot_alert_message(msg_text, title=msg_title, tags=msg_tags):
                        continue

                    log.info(f"Processing ntfy command: '{msg_text}' (id={msg_id})")
                    res = self.handle_command(msg_text)
                    if res:
                        reply_body, reply_title, reply_priority = res
                        self.publish_response(
                            message=reply_body,
                            title=reply_title,
                            priority=reply_priority,
                        )

            except requests.RequestException as e:
                log.debug(f"ntfy stream disconnected ({e}). Reconnecting in 3s...")
                if self._stop_event.wait(3.0):
                    break
            except Exception as e:
                log.error(f"Unexpected error in ntfy stream listener: {e}", exc_info=True)
                if self._stop_event.wait(5.0):
                    break

        log.info("ntfy stream listener exited.")

    def start(self) -> bool:
        """Starts the ntfy listener in a background daemon thread."""
        if not self.is_configured:
            log.warning("NTFY_TOPIC is not set. ntfy remote control is disabled.")
            return False

        if self.is_running:
            return False

        self._stop_event.clear()
        self._thread = threading.Thread(target=self._stream_loop, name="ntfy_stream_poller", daemon=True)
        self._thread.start()
        log.info(f"ntfy Two-Way Controller is ACTIVE on topic: '{self.topic}'")
        return True

    def stop(self) -> None:
        """Stops the ntfy listener thread cleanly."""
        self._stop_event.set()
        if self._thread and self._thread.is_alive():
            self._thread.join(timeout=3.0)
        log.info("ntfy Two-Way Controller stopped.")
